eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:6111/eureka/
server:
  port: 8081
spring:
  application:
    name: my-account-service
  h2:
    console:
      enabled: true
      path: /h2
