server:
  port: 8087
spring:
  application:
    name: service-A
  cloud:
    consul:
      discovery:
        register: true
        service-name: service-A
      host: localhost
      port: 8500