server:
  port: 8763
spring:  application:    name: image-service  h2:    console:      enabled: true
      path: /h2
eureka:
  client:
    serviceUrl:

      defaultZone: http://localhost:8761/eureka/
      register-with-eureka: true
      

      
    
