server:
  port: 8505
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
  application:
    name: student-service
  cloud:
    consul:
      discovery:
        register: true
        service-name: student-service
      host: localhost
      port: 8500
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: Tata123!
   